---
- name: download blender
  get_url:
    url: "https://download.blender.org/release/Blender{{install_blender_version}}/blender-{{install_blender_version}}-linux-glibc{{install_blender_glibc_version}}-x86_64.tar.bz2"
    dest: "/root/blender-{{install_blender_version}}-stable.tar.bz2"
    checksum: "{{install_blender_checksum}}"

- name: unpack installer
  unarchive:
    src: "/root/blender-{{install_blender_version}}-stable.tar.bz2"
    dest: /usr/local/
    remote_src: yes
    creates: "/usr/local/blender-{{install_blender_version}}-linux-glibc{{install_blender_glibc_version}}-x86_64"
    owner: root
    group: root

- name: create symlink to blender folder
  file:
    src: "/usr/local/blender-{{install_blender_version}}-linux-glibc{{install_blender_glibc_version}}-x86_64"
    dest: "/usr/local/blender"
    state: link

- name: create symlinks to binaries
  file:
    src: "/usr/local/blender/{{item}}"
    dest: "/usr/local/bin/{{item}}"
    state: link
  with_items:
    - blender
    - blenderplayer
    - blender-softwaregl
    - blender-thumbnailer.py
